const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

/**
 * 构建时脚本：将YAML配置转换为TypeScript文件
 * 这确保了配置在Vercel等无服务器环境中可用
 */
function buildConfig() {
  try {
    // 确定项目根目录
    const projectRoot = path.dirname(__dirname)
    
    // 读取YAML配置
    const configPath = path.join(projectRoot, 'config.yaml')
    console.log(`Looking for config at: ${configPath}`)
    
    if (!fs.existsSync(configPath)) {
      throw new Error(`Config file not found at: ${configPath}`)
    }
    
    const yamlContent = fs.readFileSync(configPath, 'utf8')
    const config = yaml.load(yamlContent)

    // 生成TypeScript配置文件
    const tsContent = `// 此文件由构建脚本自动生成，请勿手动编辑
// Generated by scripts/build-config.js

import type { SiteConfig } from './config'

export const buildTimeConfig: SiteConfig = ${JSON.stringify(config, null, 2)} as SiteConfig
`

    // 写入生成的配置文件
    const outputPath = path.join(projectRoot, 'src/lib/generated-config.ts')
    fs.writeFileSync(outputPath, tsContent, 'utf8')

    console.log('✅ Configuration compiled successfully to src/lib/generated-config.ts')
  } catch (error) {
    console.error('❌ Failed to compile configuration:', error)
    process.exit(1)
  }
}

// 如果直接运行此脚本
if (require.main === module) {
  buildConfig()
}

module.exports = buildConfig